const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.TEST_URL || 'http://127.0.0.1:4173/';
(async () => {
 const browser = await chromium.launch({ headless: true, channel: 'msedge' });
 try {
  fs.mkdirSync('test-results', { recursive: true });
  const context = await browser.newContext({ viewport: { width: 375, height: 850 }, hasTouch: true });
  await context.addInitScript(() => { if (!localStorage.getItem('train-hiragana-v1')) localStorage.setItem('train-hiragana-v1', JSON.stringify({ sound: false })); });
  const page = await context.newPage(), errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const state = () => page.evaluate(() => history.state.connectState);
  const click = action => page.locator('[data-connect="' + action + '"]').first().click();
  const waitInput = () => page.waitForFunction(() => Date.now() >= (history.state.connectState.lockedUntil || 0) && !document.querySelector('.connect-letter')?.disabled);
  const complete = async () => {
   while ((await state()).phase === 'build') {
    await waitInput();
    const letter = await page.locator('.connect-car.waiting .connect-ghost').textContent();
    await page.locator('[data-connect="letter"][data-letter="' + letter + '"]').click();
   }
  };
  const noOverflow = async () => assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.goto(base);
  await page.locator('[data-action="start-connect"]').click();
  await page.locator('[data-connect="choose"][data-id="komachi"]').click();
  assert.equal((await state()).index, 0);
  assert.equal(await page.locator('.connect-letter').count(), 1);
  assert.equal(await page.locator('[data-connect="depart"]').count(), 0);
  await page.locator('.connect-letter').tap();
  assert.equal((await state()).index, 1);
  assert.equal(await page.locator('.assembly-car.coupled').count(), 1);
  assert.equal(await page.locator('.assembly-car.incoming').evaluate(el => getComputedStyle(el).animationName), 'assembly-couple');
  await page.screenshot({ path: 'test-results/connect-komachi-coupling-mobile.png', fullPage: true });
  // A rapid duplicate input cannot skip the next carriage.
  await page.locator('.connect-letter').dispatchEvent('click');
  assert.equal((await state()).index, 1);
  await waitInput();
  const a = await page.locator('.connect-letter').boundingBox(), b = await page.locator('.connect-car.waiting').boundingBox();
  const cdp = await context.newCDPSession(page);
  await cdp.send('Input.dispatchTouchEvent', { type:'touchStart', touchPoints:[{x:a.x+25,y:a.y+25,id:1}] });
  await cdp.send('Input.dispatchTouchEvent', { type:'touchMove', touchPoints:[{x:b.x+25,y:b.y+25,id:1}] });
  await cdp.send('Input.dispatchTouchEvent', { type:'touchEnd', touchPoints:[] });
  assert.equal((await state()).index, 2);
  await page.locator('[data-action="settings"]').click();
  await page.goBack();
  assert.equal((await state()).index, 2);
  assert.ok((await state()).lockedUntil - Date.now() <= 1800, 'returning never preserves the temporary 20-second audio lock');
  await complete();
  assert.equal((await state()).completedCards.length, 1);
  await page.waitForTimeout(1400);
  assert.equal(await page.locator('.reward-dialog').count(), 0);
  assert.equal(await page.locator('.assembly-car.coupled').count(), 3);
  await page.screenshot({ path: 'test-results/connect-komachi-complete-mobile.png', fullPage: true });
  await noOverflow();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path:'test-results/connect-komachi-desktop.png', fullPage:true });
  await page.setViewportSize({ width:375, height:850 });
  await click('next');
  const target = await page.locator('.connect-ghost').textContent();
  const wrong = page.locator('.connect-letter').filter({ hasText: new RegExp('^(?!' + target + '$).') }).first();
  await wrong.click();
  assert.equal((await state()).index, 0);
  await click('hint');
  assert.equal(await page.locator('.connect-letter').count(), 1);
  await page.locator('[data-action="home"]').first().click();
  await page.locator('[data-action="start-connect"]').click();
  assert.equal((await state()).completedCards.length, 1);
  await click('garage');
  await click('resume');
  await complete();
  assert.equal((await state()).completedCards.length, 2);
  await page.reload();
  assert.equal((await state()).completedCards.length, 2);
  assert.equal(await page.locator('.reward-dialog').count(), 0);
  await click('next');
  await complete();
  assert.equal(await page.locator('.reward-dialog').count(), 0);
  assert.equal(await page.locator('.connect-next').isDisabled(), true);
  await page.waitForTimeout(2000);
  assert.equal(await page.locator('.reward-dialog').count(), 0);
  await click('next');
  await page.locator('.reward-dialog').waitFor();
  assert.equal(await page.locator('.earned-trains>div').count(), 3);
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('train-hiragana-v1')).trips), 1);
  await page.locator('[data-reward="continue"]').click();
  await page.waitForTimeout(1500);
  assert.equal(await page.locator('.reward-dialog').count(), 0);
  await page.locator('[data-action="start-connect"]').click();
  await page.locator('[data-connect="choose"][data-id="komachi"]').click();
  assert.equal((await state()).completedCards.length, 0);
  await click('garage');
  assert.equal(await page.locator('.connect-train').count(), 3);
  await click('pick');
  await page.locator('.connect-more summary').click();
  await page.locator('[data-connect="choose"][data-id="heisei-chikuho"]').click();
  await page.setViewportSize({ width:320,height:740 });
  await noOverflow();
  await complete();
  await noOverflow();
  await page.screenshot({ path:'test-results/connect-long-mobile.png', fullPage:true });
  assert.ok(await page.locator('[data-connect="next"]').evaluate(el => el.getBoundingClientRect().bottom <= innerHeight), 'next button fits screen');
  const blocked = await browser.newPage({ reducedMotion:'reduce' });
  await blocked.addInitScript(() => Object.defineProperty(window,'localStorage',{get(){throw Error('blocked');}}));
  await blocked.goto(base);
  await blocked.locator('[data-action="start-connect"]').click();
  await blocked.locator('[data-connect="choose"][data-id="komachi"]').click();
  for (let i=0;i<3;i++) { await blocked.waitForFunction(() => Date.now() >= (history.state.connectState.lockedUntil || 0)); await blocked.locator('.connect-letter').click(); }
  assert.equal(await blocked.locator('.connect-save').count(), 1);
  assert.equal(await blocked.locator('.assembly-car.incoming').evaluate(el => getComputedStyle(el).animationName), 'none');
  assert.deepEqual(errors, []);
  console.log('Connect checks passed: guided Komachi assembly, normal animation, touch drag, double taps, 3-name reward only once, Back/reload/resume, garage, long names, blocked storage, reduced motion.');
 } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode=1; });
