"""Validate and compress generated Flash-Lite WAVs, then publish a complete manifest.
Requires imageio-ffmpeg (or --ffmpeg PATH). Raw WAVs remain local.
"""
import argparse, concurrent.futures, hashlib, importlib.util, json, os, struct, subprocess
from pathlib import Path

ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/'assets/voice/announcements-lite'
MODEL='gemini-3.8-flash-lite-tts'
spec=importlib.util.spec_from_file_location('voice_generation',ROOT/'scripts/generate-announcements.py')
generation=importlib.util.module_from_spec(spec);spec.loader.exec_module(generation)

def publish_text(path,text):
    temporary=path.with_suffix(path.suffix+'.tmp')
    temporary.write_text(text,encoding='utf-8')
    generation.replace_file(temporary,path)

def main():
    parser=argparse.ArgumentParser(__doc__);parser.add_argument('--ffmpeg');args=parser.parse_args()
    if args.ffmpeg:ffmpeg=args.ffmpeg
    else:
        import imageio_ffmpeg
        ffmpeg=imageio_ffmpeg.get_ffmpeg_exe()
    lines=json.loads((ROOT/'assets/voice/lines.json').read_text(encoding='utf-8'))['lines']
    def encode(line):
        stem=hashlib.sha256(line['text'].encode()).hexdigest()[:16];source=OUT/(stem+'.wav');target=OUT/(stem+'.mp3')
        def encode_source():
            if not source.exists():raise ValueError('Missing generated clip: '+line['text'])
            if not generation.valid_audio(source):raise ValueError('Invalid generated source: '+line['text'])
            temporary=target.with_suffix('.tmp.mp3')
            subprocess.run([ffmpeg,'-nostdin','-hide_banner','-loglevel','error','-y','-i',str(source),'-codec:a','libmp3lame','-b:a','64k','-ar','24000','-ac','1',str(temporary)],check=True)
            generation.replace_file(temporary,target)
        if not target.exists() or source.exists() and source.stat().st_mtime>target.stat().st_mtime:
            encode_source()
        def decode_target():
            return subprocess.check_output([ffmpeg,'-nostdin','-hide_banner','-loglevel','error','-i',str(target),'-f','s16le','-ac','1','-ar','24000','pipe:1'])
        try:pcm=decode_target()
        except subprocess.CalledProcessError:
            # An interrupted previous conversion must not poison resumability.
            encode_source();pcm=decode_target()
        samples=struct.unpack('<'+'h'*(len(pcm)//2),pcm)
        if not samples or max(abs(value) for value in samples)<500:raise ValueError('Silent compressed clip: '+line['text'])
        stats={'text':line['text'],'duration':len(samples)/24000,'peak':max(abs(value) for value in samples)/32768,
               'rms':(sum(value*value for value in samples)/len(samples))**.5/32768}
        return line['text'],'announcements-lite/'+target.name,stats
    files={};quality=[]
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:
        for i,(text,file,stats) in enumerate(pool.map(encode,lines),1):
            files[text]=file;quality.append(stats)
            if i%100==0:print('Compressed and verified',i,'/',len(lines),flush=True)
    manifest={'model':MODEL,'voice':'Kore','style':generation.STYLE,'codec':'MP3 64kbps 24kHz mono','files':files}
    publish_text(OUT/'manifest.json',json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
    publish_text(ROOT/'src/announcement-manifest.js','// Generated by scripts/publish-announcements.py\nexport const ANNOUNCEMENT_FILES = '+json.dumps(files,ensure_ascii=False,indent=2)+';\n')
    report=ROOT/'.tools/voice-audio-quality.json'
    report.parent.mkdir(exist_ok=True)
    publish_text(report,json.dumps({'model':MODEL,'clips':quality},ensure_ascii=False,indent=2)+'\n')
    print('Published all',len(files),'Flash-Lite TTS clips; total bytes:',sum((ROOT/'assets/voice'/file).stat().st_size for file in files.values()))

if __name__=='__main__':main()
